-- Create FAQs table
CREATE TABLE IF NOT EXISTS faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert initial FAQs
INSERT INTO faqs (question, answer, display_order) VALUES
(
    'Can a trip have more than two people?',
    'Yes. You can decide how may people can join the trip and find accommodations that match your needs.',
    1
),
(
    'Who pays for the hotel/lodging?',
    'That is to be decided amongst yourselves. Currently, HerStay does not receive or manage any money from its users. It is highly recommended that you draw up a written agreement before making any payments. As stated in the terms and conditions HerStay is not liable for any payments or agreements and is only intended to connect users with similar travel lodging preferences.',
    2
),
(
    'Can I bring my pet?',
    'That is completely up to you and your matches and your selected lodging. Please be sure to ask your trip matches if you intend to bring a pet and move accordingly.',
    3
),
(
    'Will HerStay reimburse me if my match cancels or is a no-show?',
    'No. HerStay is not liable for any agreements made in or out of the app. We recommended using written agreements. You may use the app to connect with other users who may be interested in replacing your match/es.',
    4
),
(
    'What if I cannot meet up with a match in person before agreeing to share a trip?',
    'That is a common scenario since many of you will live in different cities and states. We encourage you to meet via video call/meeting prior to proceeding with your trip. This will be done off the app.',
    5
);

-- Enable Row Level Security (RLS)
ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;

-- Create policy to allow everyone to read FAQs
CREATE POLICY "FAQs are viewable by everyone" 
ON faqs FOR SELECT 
USING (true);
