// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAazdEcg9U06zzW7gqXvTWbOm1pHSQKl88',
    appId: '1:775386424829:web:2cb40b3ac6aaead62aa594',
    messagingSenderId: '775386424829',
    projectId: 'kisaan-rk',
    authDomain: 'kisaan-rk.firebaseapp.com',
    storageBucket: 'kisaan-rk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDusLD6RGyN_PjYl0yxrDAloWGxXlsGD2s',
    appId: '1:775386424829:android:79869af76ddcd44c2aa594',
    messagingSenderId: '775386424829',
    projectId: 'kisaan-rk',
    storageBucket: 'kisaan-rk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-_y38mvRU2nC08d3JOmEo8fYH4urrms',
    appId: '1:775386424829:ios:7df771e6971f97c22aa594',
    messagingSenderId: '775386424829',
    projectId: 'kisaan-rk',
    storageBucket: 'kisaan-rk.firebasestorage.app',
    iosBundleId: 'com.example.kisanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO-_y38mvRU2nC08d3JOmEo8fYH4urrms',
    appId: '1:775386424829:ios:7df771e6971f97c22aa594',
    messagingSenderId: '775386424829',
    projectId: 'kisaan-rk',
    storageBucket: 'kisaan-rk.firebasestorage.app',
    iosBundleId: 'com.example.kisanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAazdEcg9U06zzW7gqXvTWbOm1pHSQKl88',
    appId: '1:775386424829:web:09eff1030ef532702aa594',
    messagingSenderId: '775386424829',
    projectId: 'kisaan-rk',
    authDomain: 'kisaan-rk.firebaseapp.com',
    storageBucket: 'kisaan-rk.firebasestorage.app',
  );

}